### ISSUE TITLE
Waah! No vanilla go run :( PPPPPpppppp

### ISSUE THREAD

**Issue by ghost** [revolucas/CoC-Xray#1]
stack traceback:
	d:\game\gamedata\scripts\_g.script:854: in function 'callstack'
	d:\game\gamedata\scripts\sim_board.script:322: in function 'enter_smart'
	d:\game\gamedata\scripts\smart_terrain.script:1386: in function 'call_respawn'
	d:\game\gamedata\scripts\smart_terrain.script:1408: in function 'try_respawn'
	d:\game\gamedata\scripts\smart_terrain.script:1022: in function 'update'
	d:\game\gamedata\scripts\bind_smart_terrain.script:69: in function <d:\game\gamedata\scripts\bind_smart_terrain.script:66>
	[C]: in function 'set_callback'
	d:\game\gamedata\scripts\bind_stalker.script:144: in function <d:\game\gamedata\scripts\bind_stalker.script:124>
2
stack traceback:
	d:\game\gamedata\scripts\_g.script:854: in function 'callstack'
	d:\game\gamedata\scripts\sim_board.script:322: in function 'enter_smart'
	d:\game\gamedata\scripts\smart_terrain.script:1386: in function 'call_respawn'
	d:\game\gamedata\scripts\smart_terrain.script:1408: in function 'try_respawn'
	d:\game\gamedata\scripts\smart_terrain.script:1022: in function 'update'
	d:\game\gamedata\scripts\bind_smart_terrain.script:69: in function <d:\game\gamedata\scripts\bind_smart_terrain.script:66>
	[C]: in function 'set_callback'
	d:\game\gamedata\scripts\bind_stalker.script:144: in function <d:\game\gamedata\scripts\bind_stalker.script:124>
2
stack traceback:
	d:\game\gamedata\scripts\_g.script:854: in function 'callstack'
	d:\game\gamedata\scripts\sim_board.script:322: in function 'enter_smart'
	d:\game\gamedata\scripts\smart_terrain.script:1386: in function 'call_respawn'
	d:\game\gamedata\scripts\smart_terrain.script:1408: in function 'try_respawn'
	d:\game\gamedata\scripts\smart_terrain.script:1022: in function 'update'
	d:\game\gamedata\scripts\bind_smart_terrain.script:69: in function <d:\game\gamedata\scripts\bind_smart_terrain.script:66>
	[C]: in function 'set_callback'
	d:\game\gamedata\scripts\bind_stalker.script:144: in function <d:\game\gamedata\scripts\bind_stalker.script:124>
! [SCRIPT ERROR]: d:\game\gamedata\scripts\smart_terrain_control.script:65: attempt to index field 'actor' (a nil value)
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_error
[error]File          : ..\xrServerEntities\script_engine.cpp
[error]Line          : 189
[error]Description   : fatal error
[error]Arguments     : LUA error: d:\game\gamedata\scripts\smart_terrain_control.script:65: attempt to index field 'actor' (a nil value)
 

stack trace:

0023:022A394C xrCore.dll, xrDebug::fatal(), i:\coc-xray-working\src\xrcore\xrdebugnew.cpp, 411
0023:0A7333E2 xrGame.dll, CScriptEngine::lua_error(), i:\coc-xray-working\src\xrserverentities\script_engine.cpp, 189
0023:0AA9BA59 xrGame.dll, luabind::class_<CScriptXmlInit,luabind::detail::unspecified,luabind::detail::unspecified,luabind::detail::unspecified>::virtual_def<CUICheckButton * (__thiscall CScriptXmlInit::*)(char const *,CUIWindow *),luabind::detail::null_type>(), i:\coc-xray-working\src\3rd party\luabind\luabind\class.hpp, 1207

**Comment by revolucas** [comment]
Fixed in d624f6189a9b6ef499d46a18ca97e2eecfed4c6a
