### ISSUE TITLE
luabind/lua  passing invalid params to engine functions

### ISSUE THREAD

**Issue by revolucas** [revolucas/CoC-Xray#11]
I need someone more experienced to fix or tell me why when passing an invalid or unexpected type to engine function, lua script just silently stops working without warning or error, making it extremely difficult to detect this kind of mistake or error.

For example, when doing something like:

db.actor:give_game_news("test_caption", "text", nil, 500, 10, 1)

If passing nil instead of a string for the third param, game will run fine, except whatever script this occurred in just stops working without warning. Is there a way to error check this?

**Comment by Xottab-DUTY** [comment]
That's not a very good decision, but you can just update Luabind to a new version...

The result would be engine crash on wrong script instead of just script stopping.
