### ISSUE TITLE
DX8 (renderer_r1)

### ISSUE THREAD

**Issue by revolucas** [revolucas/CoC-Xray#18]
`stack trace:

0023:041E430A xrRender_R1.dll, CLightProjector::calculate(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\layers\xrrenderpc_r1\lightprojector.cpp, 182
0023:041D75D0 xrRender_R1.dll, CRender::Calculate(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\layers\xrrenderpc_r1\fstaticrender.cpp, 537
0023:0042ACE8 xrEngine.exe, IGame_Level::OnRender(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\igame_level.cpp, 167
0023:049B73A9 xrGame.dll, CLevel::OnRender(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrgame\level.cpp, 692
0023:0041109C xrEngine.exe, CRegistrator<pureRender>::Process(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\pure.h, 90
0023:00410872 xrEngine.exe, CRenderDevice::on_idle(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\device.cpp, 291
0023:004109EA xrEngine.exe, CRenderDevice::message_loop(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\device.cpp, 345
0023:00410B0E xrEngine.exe, CRenderDevice::Run(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\device.cpp, 395
0023:004650ED xrEngine.exe, Startup(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\x_ray.cpp, 390
0023:00465873 xrEngine.exe, WinMain_impl(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\x_ray.cpp, 889
0023:00465976 xrEngine.exe, WinMain(), e:\stalker\x-ray source\x-ray_callofchernobyl\src\xrengine\x_ray.cpp, 958
0023:0047157B xrEngine.exe, __tmainCRTStartup(), f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c, 618
0023:77367C04 KERNEL32.DLL, BaseThreadInitThunk()
0023:775BAD1F ntdll.dll, RtlInitializeExceptionChain()
0023:775BACEA ntdll.dll, RtlInitializeExceptionChain()
 
[error][      87] : The parameter is incorrect.
`

When switching to another renderer from r1 and trying to load a game

**Comment by ghost** [comment]
@revolucas When this happens, are you switching from r1 to r2.5/3/4 without a restart, or is this after the game restarts?

**Comment by Xottab-DUTY** [comment]
Was this fixed?
