### ISSUE TITLE
models\lightplanes

### ISSUE THREAD

**Issue by revolucas** [revolucas/CoC-Xray#21]
https://github.com/revolucas/CoC-Xray/pull/20#issuecomment-403728088

Works correctly for World mesh. But it does not work correctly for HUD.

**Comment by revolucas** [comment]
Issue seems to be that the glow is rendered in normal mode and not in hud mode. I do not know where to begin to correct this.

**Comment by Xottab-DUTY** [comment]
https://github.com/OpenXRay/xray-16/commit/9ab3eae49622c8b3912a42f43eba5cd1f2580d08
https://github.com/xrOxygen/xray-oxygen/commit/6550c5c895ea06b21ed6fa1d315c61fae5758d62

**Comment by revolucas** [comment]
Thanks buddy
